/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.ClusterDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClusterDetails', function() {
    it('should create an instance of ClusterDetails', function() {
      // uncomment below and update the code to test ClusterDetails
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be.a(JourneyOrchestrationApi.ClusterDetails);
    });

    it('should have the property nodeName (base name: "nodeName")', function() {
      // uncomment below and update the code to test the property nodeName
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property publicIp (base name: "public_ip")', function() {
      // uncomment below and update the code to test the property publicIp
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property lastSeen (base name: "lastSeen")', function() {
      // uncomment below and update the code to test the property lastSeen
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property restartCount (base name: "restartCount")', function() {
      // uncomment below and update the code to test the property restartCount
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property host (base name: "host")', function() {
      // uncomment below and update the code to test the property host
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property firstDownTime (base name: "firstDownTime")', function() {
      // uncomment below and update the code to test the property firstDownTime
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property nodeDescription (base name: "nodeDescription")', function() {
      // uncomment below and update the code to test the property nodeDescription
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property reportedBy (base name: "reportedBy")', function() {
      // uncomment below and update the code to test the property reportedBy
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property consistency (base name: "consistency")', function() {
      // uncomment below and update the code to test the property consistency
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property bootstrapVersion (base name: "bootstrapVersion")', function() {
      // uncomment below and update the code to test the property bootstrapVersion
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

    it('should have the property serverSettings (base name: "serverSettings")', function() {
      // uncomment below and update the code to test the property serverSettings
      //var instance = new JourneyOrchestrationApi.ClusterDetails();
      //expect(instance).to.be();
    });

  });

}));
