/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.ConsistencyReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConsistencyReport', function() {
    it('should create an instance of ConsistencyReport', function() {
      // uncomment below and update the code to test ConsistencyReport
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be.a(JourneyOrchestrationApi.ConsistencyReport);
    });

    it('should have the property objectType (base name: "objectType")', function() {
      // uncomment below and update the code to test the property objectType
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property isConsistent (base name: "isConsistent")', function() {
      // uncomment below and update the code to test the property isConsistent
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property localCount (base name: "localCount")', function() {
      // uncomment below and update the code to test the property localCount
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property remoteCount (base name: "remoteCount")', function() {
      // uncomment below and update the code to test the property remoteCount
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property missingRemotely (base name: "missingRemotely")', function() {
      // uncomment below and update the code to test the property missingRemotely
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property missingLocally (base name: "missingLocally")', function() {
      // uncomment below and update the code to test the property missingLocally
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property differentLocally (base name: "differentLocally")', function() {
      // uncomment below and update the code to test the property differentLocally
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

    it('should have the property reportedExceptions (base name: "reportedExceptions")', function() {
      // uncomment below and update the code to test the property reportedExceptions
      //var instance = new JourneyOrchestrationApi.ConsistencyReport();
      //expect(instance).to.be();
    });

  });

}));
