/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.PercentileStatistics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PercentileStatistics', function() {
    it('should create an instance of PercentileStatistics', function() {
      // uncomment below and update the code to test PercentileStatistics
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be.a(JourneyOrchestrationApi.PercentileStatistics);
    });

    it('should have the property p10 (base name: "p10")', function() {
      // uncomment below and update the code to test the property p10
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p20 (base name: "p20")', function() {
      // uncomment below and update the code to test the property p20
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p30 (base name: "p30")', function() {
      // uncomment below and update the code to test the property p30
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p40 (base name: "p40")', function() {
      // uncomment below and update the code to test the property p40
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p50 (base name: "p50")', function() {
      // uncomment below and update the code to test the property p50
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p60 (base name: "p60")', function() {
      // uncomment below and update the code to test the property p60
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p70 (base name: "p70")', function() {
      // uncomment below and update the code to test the property p70
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p80 (base name: "p80")', function() {
      // uncomment below and update the code to test the property p80
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p90 (base name: "p90")', function() {
      // uncomment below and update the code to test the property p90
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property p99 (base name: "p99")', function() {
      // uncomment below and update the code to test the property p99
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

    it('should have the property min (base name: "min")', function() {
      // uncomment below and update the code to test the property min
      //var instance = new JourneyOrchestrationApi.PercentileStatistics();
      //expect(instance).to.be();
    });

  });

}));
