/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.QueueField();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueueField', function() {
    it('should create an instance of QueueField', function() {
      // uncomment below and update the code to test QueueField
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be.a(JourneyOrchestrationApi.QueueField);
    });

    it('should have the property isSystem (base name: "isSystem")', function() {
      // uncomment below and update the code to test the property isSystem
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property streamKey (base name: "streamKey")', function() {
      // uncomment below and update the code to test the property streamKey
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property indexLevel (base name: "indexLevel")', function() {
      // uncomment below and update the code to test the property indexLevel
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property storageHint (base name: "storageHint")', function() {
      // uncomment below and update the code to test the property storageHint
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property dataType (base name: "dataType")', function() {
      // uncomment below and update the code to test the property dataType
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property issankey (base name: "issankey")', function() {
      // uncomment below and update the code to test the property issankey
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property precision (base name: "precision")', function() {
      // uncomment below and update the code to test the property precision
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

    it('should have the property keyName (base name: "keyName")', function() {
      // uncomment below and update the code to test the property keyName
      //var instance = new JourneyOrchestrationApi.QueueField();
      //expect(instance).to.be();
    });

  });

}));
