/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.QueueListing();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueueListing', function() {
    it('should create an instance of QueueListing', function() {
      // uncomment below and update the code to test QueueListing
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be.a(JourneyOrchestrationApi.QueueListing);
    });

    it('should have the property fifo (base name: "fifo")', function() {
      // uncomment below and update the code to test the property fifo
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property queueBackend (base name: "queueBackend")', function() {
      // uncomment below and update the code to test the property queueBackend
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property client (base name: "client")', function() {
      // uncomment below and update the code to test the property client
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property lock (base name: "lock")', function() {
      // uncomment below and update the code to test the property lock
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property statusMessage (base name: "statusMessage")', function() {
      // uncomment below and update the code to test the property statusMessage
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property numMessages (base name: "numMessages")', function() {
      // uncomment below and update the code to test the property numMessages
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new JourneyOrchestrationApi.QueueListing();
      //expect(instance).to.be();
    });

  });

}));
