/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.Statistics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Statistics', function() {
    it('should create an instance of Statistics', function() {
      // uncomment below and update the code to test Statistics
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be.a(JourneyOrchestrationApi.Statistics);
    });

    it('should have the property bulkLoad (base name: "bulkLoad")', function() {
      // uncomment below and update the code to test the property bulkLoad
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property cumulativeInvokeTime (base name: "cumulativeInvokeTime")', function() {
      // uncomment below and update the code to test the property cumulativeInvokeTime
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property errorCount (base name: "errorCount")', function() {
      // uncomment below and update the code to test the property errorCount
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property errorCountHealthScore (base name: "errorCountHealthScore")', function() {
      // uncomment below and update the code to test the property errorCountHealthScore
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property healthScore (base name: "healthScore")', function() {
      // uncomment below and update the code to test the property healthScore
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property invalidCount (base name: "invalidCount")', function() {
      // uncomment below and update the code to test the property invalidCount
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property invokeCountHealthScore (base name: "invokeCountHealthScore")', function() {
      // uncomment below and update the code to test the property invokeCountHealthScore
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property invalidDataCountHealthScore (base name: "invalidDataCountHealthScore")', function() {
      // uncomment below and update the code to test the property invalidDataCountHealthScore
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property invokeCount (base name: "invokeCount")', function() {
      // uncomment below and update the code to test the property invokeCount
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property newActiveConversation (base name: "newActiveConversation")', function() {
      // uncomment below and update the code to test the property newActiveConversation
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property newConversation (base name: "newConversation")', function() {
      // uncomment below and update the code to test the property newConversation
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property rosCounts (base name: "rosCounts")', function() {
      // uncomment below and update the code to test the property rosCounts
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property serviceCost (base name: "serviceCost")', function() {
      // uncomment below and update the code to test the property serviceCost
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property totalTimeouts (base name: "totalTimeouts")', function() {
      // uncomment below and update the code to test the property totalTimeouts
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property totalTimeoutsHealthScore (base name: "totalTimeoutsHealthScore")', function() {
      // uncomment below and update the code to test the property totalTimeoutsHealthScore
      //var instance = new JourneyOrchestrationApi.Statistics();
      //expect(instance).to.be();
    });

  });

}));
