/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.FileApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileApi', function() {
    describe('fileClientGet', function() {
      it('should call fileClientGet successfully', function(done) {
        //uncomment below and update the code to test fileClientGet
        //instance.fileClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileClientTargetFilenameDelete', function() {
      it('should call fileClientTargetFilenameDelete successfully', function(done) {
        //uncomment below and update the code to test fileClientTargetFilenameDelete
        //instance.fileClientTargetFilenameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileClientTargetFilenameGet', function() {
      it('should call fileClientTargetFilenameGet successfully', function(done) {
        //uncomment below and update the code to test fileClientTargetFilenameGet
        //instance.fileClientTargetFilenameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileClientTargetFilenamePost', function() {
      it('should call fileClientTargetFilenamePost successfully', function(done) {
        //uncomment below and update the code to test fileClientTargetFilenamePost
        //instance.fileClientTargetFilenamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileClientTargetGet', function() {
      it('should call fileClientTargetGet successfully', function(done) {
        //uncomment below and update the code to test fileClientTargetGet
        //instance.fileClientTargetGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
