/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.GlobalparameterApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GlobalparameterApi', function() {
    describe('downloadGlobalparameterClientParamnameGet', function() {
      it('should call downloadGlobalparameterClientParamnameGet successfully', function(done) {
        //uncomment below and update the code to test downloadGlobalparameterClientParamnameGet
        //instance.downloadGlobalparameterClientParamnameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientGet', function() {
      it('should call globalparameterClientGet successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientGet
        //instance.globalparameterClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientParamnameCopyPost', function() {
      it('should call globalparameterClientParamnameCopyPost successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientParamnameCopyPost
        //instance.globalparameterClientParamnameCopyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientParamnameCopyPut', function() {
      it('should call globalparameterClientParamnameCopyPut successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientParamnameCopyPut
        //instance.globalparameterClientParamnameCopyPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientParamnameDelete', function() {
      it('should call globalparameterClientParamnameDelete successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientParamnameDelete
        //instance.globalparameterClientParamnameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientParamnameGet', function() {
      it('should call globalparameterClientParamnameGet successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientParamnameGet
        //instance.globalparameterClientParamnameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterClientParamnamePut', function() {
      it('should call globalparameterClientParamnamePut successfully', function(done) {
        //uncomment below and update the code to test globalparameterClientParamnamePut
        //instance.globalparameterClientParamnamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterGet', function() {
      it('should call globalparameterGet successfully', function(done) {
        //uncomment below and update the code to test globalparameterGet
        //instance.globalparameterGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('globalparameterPost', function() {
      it('should call globalparameterPost successfully', function(done) {
        //uncomment below and update the code to test globalparameterPost
        //instance.globalparameterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
