/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.InfoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InfoApi', function() {
    describe('infoAuditlogClientGet', function() {
      it('should call infoAuditlogClientGet successfully', function(done) {
        //uncomment below and update the code to test infoAuditlogClientGet
        //instance.infoAuditlogClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoCachedataClientGet', function() {
      it('should call infoCachedataClientGet successfully', function(done) {
        //uncomment below and update the code to test infoCachedataClientGet
        //instance.infoCachedataClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoCacheunusedcolumnsClientGet', function() {
      it('should call infoCacheunusedcolumnsClientGet successfully', function(done) {
        //uncomment below and update the code to test infoCacheunusedcolumnsClientGet
        //instance.infoCacheunusedcolumnsClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoClientaccessreportClientGet', function() {
      it('should call infoClientaccessreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoClientaccessreportClientGet
        //instance.infoClientaccessreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoConsistencyreportGet', function() {
      it('should call infoConsistencyreportGet successfully', function(done) {
        //uncomment below and update the code to test infoConsistencyreportGet
        //instance.infoConsistencyreportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoConversationusagereportClientTimeseriesGet', function() {
      it('should call infoConversationusagereportClientTimeseriesGet successfully', function(done) {
        //uncomment below and update the code to test infoConversationusagereportClientTimeseriesGet
        //instance.infoConversationusagereportClientTimeseriesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoFieldusageTargetClientRulenameGet', function() {
      it('should call infoFieldusageTargetClientRulenameGet successfully', function(done) {
        //uncomment below and update the code to test infoFieldusageTargetClientRulenameGet
        //instance.infoFieldusageTargetClientRulenameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoFlowTargetClientRulenameGet', function() {
      it('should call infoFlowTargetClientRulenameGet successfully', function(done) {
        //uncomment below and update the code to test infoFlowTargetClientRulenameGet
        //instance.infoFlowTargetClientRulenameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoGlobalparamreportClientGet', function() {
      it('should call infoGlobalparamreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoGlobalparamreportClientGet
        //instance.infoGlobalparamreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoInternalrulecallreportClientTargetRulenameGet', function() {
      it('should call infoInternalrulecallreportClientTargetRulenameGet successfully', function(done) {
        //uncomment below and update the code to test infoInternalrulecallreportClientTargetRulenameGet
        //instance.infoInternalrulecallreportClientTargetRulenameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoLogged404sClientGet', function() {
      it('should call infoLogged404sClientGet successfully', function(done) {
        //uncomment below and update the code to test infoLogged404sClientGet
        //instance.infoLogged404sClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoResourceexistsreportPost', function() {
      it('should call infoResourceexistsreportPost successfully', function(done) {
        //uncomment below and update the code to test infoResourceexistsreportPost
        //instance.infoResourceexistsreportPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoRulecomplexityreportClientGet', function() {
      it('should call infoRulecomplexityreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoRulecomplexityreportClientGet
        //instance.infoRulecomplexityreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoSnoozeGet', function() {
      it('should call infoSnoozeGet successfully', function(done) {
        //uncomment below and update the code to test infoSnoozeGet
        //instance.infoSnoozeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoSteptypestatisticsDelete', function() {
      it('should call infoSteptypestatisticsDelete successfully', function(done) {
        //uncomment below and update the code to test infoSteptypestatisticsDelete
        //instance.infoSteptypestatisticsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoSteptypestatisticsGet', function() {
      it('should call infoSteptypestatisticsGet successfully', function(done) {
        //uncomment below and update the code to test infoSteptypestatisticsGet
        //instance.infoSteptypestatisticsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoSteptypeusagereportClientGet', function() {
      it('should call infoSteptypeusagereportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoSteptypeusagereportClientGet
        //instance.infoSteptypeusagereportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoStepusagereportClientStepnameGet', function() {
      it('should call infoStepusagereportClientStepnameGet successfully', function(done) {
        //uncomment below and update the code to test infoStepusagereportClientStepnameGet
        //instance.infoStepusagereportClientStepnameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoTemplatecolumnreportClientGet', function() {
      it('should call infoTemplatecolumnreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoTemplatecolumnreportClientGet
        //instance.infoTemplatecolumnreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoTemplateinputreportClientGet', function() {
      it('should call infoTemplateinputreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoTemplateinputreportClientGet
        //instance.infoTemplateinputreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoTemplateusagereportClientTemplatenameGet', function() {
      it('should call infoTemplateusagereportClientTemplatenameGet successfully', function(done) {
        //uncomment below and update the code to test infoTemplateusagereportClientTemplatenameGet
        //instance.infoTemplateusagereportClientTemplatenameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoTemplatevalidityreportClientGet', function() {
      it('should call infoTemplatevalidityreportClientGet successfully', function(done) {
        //uncomment below and update the code to test infoTemplatevalidityreportClientGet
        //instance.infoTemplatevalidityreportClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoTokenusereportGet', function() {
      it('should call infoTokenusereportGet successfully', function(done) {
        //uncomment below and update the code to test infoTokenusereportGet
        //instance.infoTokenusereportGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoWorkerthreadusageGet', function() {
      it('should call infoWorkerthreadusageGet successfully', function(done) {
        //uncomment below and update the code to test infoWorkerthreadusageGet
        //instance.infoWorkerthreadusageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
