/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyOrchestrationApi);
  }
}(this, function(expect, JourneyOrchestrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyOrchestrationApi.LicenseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LicenseApi', function() {
    describe('licenseClientActiveGet', function() {
      it('should call licenseClientActiveGet successfully', function(done) {
        //uncomment below and update the code to test licenseClientActiveGet
        //instance.licenseClientActiveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseClientGet', function() {
      it('should call licenseClientGet successfully', function(done) {
        //uncomment below and update the code to test licenseClientGet
        //instance.licenseClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseClientLicenseDelete', function() {
      it('should call licenseClientLicenseDelete successfully', function(done) {
        //uncomment below and update the code to test licenseClientLicenseDelete
        //instance.licenseClientLicenseDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseClientLicenseGet', function() {
      it('should call licenseClientLicenseGet successfully', function(done) {
        //uncomment below and update the code to test licenseClientLicenseGet
        //instance.licenseClientLicenseGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseClientLicensePost', function() {
      it('should call licenseClientLicensePost successfully', function(done) {
        //uncomment below and update the code to test licenseClientLicensePost
        //instance.licenseClientLicensePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseClientLicensePut', function() {
      it('should call licenseClientLicensePut successfully', function(done) {
        //uncomment below and update the code to test licenseClientLicensePut
        //instance.licenseClientLicensePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('licenseGet', function() {
      it('should call licenseGet successfully', function(done) {
        //uncomment below and update the code to test licenseGet
        //instance.licenseGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
