/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CacheFieldType from './CacheFieldType';
import CacheTableDirectionEnum from './CacheTableDirectionEnum';

/**
 * The CacheColumn model module.
 * @module com.alterian.jo.model/CacheColumn
 * @version 4.29.139
 */
class CacheColumn {
    /**
     * Constructs a new <code>CacheColumn</code>.
     * @alias module:com.alterian.jo.model/CacheColumn
     */
    constructor() { 
        
        CacheColumn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheColumn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheColumn} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheColumn} The populated <code>CacheColumn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheColumn();

            if (data.hasOwnProperty('direction')) {
                obj['direction'] = CacheTableDirectionEnum.constructFromObject(data['direction']);
            }
            if (data.hasOwnProperty('isClusteringColumn')) {
                obj['isClusteringColumn'] = ApiClient.convertToType(data['isClusteringColumn'], 'Boolean');
            }
            if (data.hasOwnProperty('isPartitionKey')) {
                obj['isPartitionKey'] = ApiClient.convertToType(data['isPartitionKey'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = CacheFieldType.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheColumn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheColumn</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.jo.model/CacheTableDirectionEnum} direction
 */
CacheColumn.prototype['direction'] = undefined;

/**
 * Is this field something that the data is physically clustered on?
 * @member {Boolean} isClusteringColumn
 * @default false
 */
CacheColumn.prototype['isClusteringColumn'] = false;

/**
 * Is this field part of the partition key?
 * @member {Boolean} isPartitionKey
 * @default false
 */
CacheColumn.prototype['isPartitionKey'] = false;

/**
 * The name of the field
 * @member {String} name
 */
CacheColumn.prototype['name'] = undefined;

/**
 * @member {module:com.alterian.jo.model/CacheFieldType} type
 */
CacheColumn.prototype['type'] = undefined;






export default CacheColumn;

