/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CacheDirectionEnum from './CacheDirectionEnum';

/**
 * The CacheDataReport model module.
 * @module com.alterian.jo.model/CacheDataReport
 * @version 4.30.49
 */
class CacheDataReport {
    /**
     * Constructs a new <code>CacheDataReport</code>.
     * @alias module:com.alterian.jo.model/CacheDataReport
     */
    constructor() { 
        
        CacheDataReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheDataReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheDataReport} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheDataReport} The populated <code>CacheDataReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheDataReport();

            if (data.hasOwnProperty('column')) {
                obj['column'] = ApiClient.convertToType(data['column'], 'String');
            }
            if (data.hasOwnProperty('rulename')) {
                obj['rulename'] = ApiClient.convertToType(data['rulename'], 'String');
            }
            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = CacheDirectionEnum.constructFromObject(data['direction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheDataReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheDataReport</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['column'] && !(typeof data['column'] === 'string' || data['column'] instanceof String)) {
            throw new Error("Expected the field `column` to be a primitive type in the JSON string but got " + data['column']);
        }
        // ensure the json data is a string
        if (data['rulename'] && !(typeof data['rulename'] === 'string' || data['rulename'] instanceof String)) {
            throw new Error("Expected the field `rulename` to be a primitive type in the JSON string but got " + data['rulename']);
        }
        // ensure the json data is a string
        if (data['table'] && !(typeof data['table'] === 'string' || data['table'] instanceof String)) {
            throw new Error("Expected the field `table` to be a primitive type in the JSON string but got " + data['table']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * @member {String} column
 */
CacheDataReport.prototype['column'] = undefined;

/**
 * @member {String} rulename
 */
CacheDataReport.prototype['rulename'] = undefined;

/**
 * @member {String} table
 */
CacheDataReport.prototype['table'] = undefined;

/**
 * @member {String} url
 */
CacheDataReport.prototype['url'] = undefined;

/**
 * @member {module:com.alterian.jo.model/CacheDirectionEnum} direction
 */
CacheDataReport.prototype['direction'] = undefined;






export default CacheDataReport;

