/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CacheField from './CacheField';
import TableTypeEnum from './TableTypeEnum';

/**
 * The CacheTableDetails model module.
 * @module com.alterian.jo.model/CacheTableDetails
 * @version 4.29.139
 */
class CacheTableDetails {
    /**
     * Constructs a new <code>CacheTableDetails</code>.
     * @alias module:com.alterian.jo.model/CacheTableDetails
     */
    constructor() { 
        
        CacheTableDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheTableDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheTableDetails} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheTableDetails} The populated <code>CacheTableDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheTableDetails();

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [CacheField]);
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], ['String']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('defaultTTL')) {
                obj['defaultTTL'] = ApiClient.convertToType(data['defaultTTL'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = TableTypeEnum.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheTableDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheTableDetails</code>.
     */
    static validateJSON(data) {
        if (data['fields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fields'])) {
                throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
            }
            // validate the optional field `fields` (array)
            for (const item of data['fields']) {
                CacheField.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['keys'])) {
            throw new Error("Expected the field `keys` to be an array in the JSON data but got " + data['keys']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:com.alterian.jo.model/CacheField>} fields
 */
CacheTableDetails.prototype['fields'] = undefined;

/**
 * @member {String} key
 */
CacheTableDetails.prototype['key'] = undefined;

/**
 * @member {Array.<String>} keys
 */
CacheTableDetails.prototype['keys'] = undefined;

/**
 * @member {String} name
 */
CacheTableDetails.prototype['name'] = undefined;

/**
 * @member {Number} defaultTTL
 */
CacheTableDetails.prototype['defaultTTL'] = undefined;

/**
 * @member {Number} size
 */
CacheTableDetails.prototype['size'] = undefined;

/**
 * @member {module:com.alterian.jo.model/TableTypeEnum} type
 */
CacheTableDetails.prototype['type'] = undefined;






export default CacheTableDetails;

