/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CacheUnusedColumn model module.
 * @module com.alterian.jo.model/CacheUnusedColumn
 * @version 4.30.49
 */
class CacheUnusedColumn {
    /**
     * Constructs a new <code>CacheUnusedColumn</code>.
     * @alias module:com.alterian.jo.model/CacheUnusedColumn
     */
    constructor() { 
        
        CacheUnusedColumn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheUnusedColumn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheUnusedColumn} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheUnusedColumn} The populated <code>CacheUnusedColumn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheUnusedColumn();

            if (data.hasOwnProperty('firstReportedNotSeen')) {
                obj['firstReportedNotSeen'] = ApiClient.convertToType(data['firstReportedNotSeen'], 'String');
            }
            if (data.hasOwnProperty('columnName')) {
                obj['columnName'] = ApiClient.convertToType(data['columnName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheUnusedColumn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheUnusedColumn</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firstReportedNotSeen'] && !(typeof data['firstReportedNotSeen'] === 'string' || data['firstReportedNotSeen'] instanceof String)) {
            throw new Error("Expected the field `firstReportedNotSeen` to be a primitive type in the JSON string but got " + data['firstReportedNotSeen']);
        }
        // ensure the json data is a string
        if (data['columnName'] && !(typeof data['columnName'] === 'string' || data['columnName'] instanceof String)) {
            throw new Error("Expected the field `columnName` to be a primitive type in the JSON string but got " + data['columnName']);
        }

        return true;
    }


}



/**
 * @member {String} firstReportedNotSeen
 */
CacheUnusedColumn.prototype['firstReportedNotSeen'] = undefined;

/**
 * @member {String} columnName
 */
CacheUnusedColumn.prototype['columnName'] = undefined;






export default CacheUnusedColumn;

