/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CacheUnusedColumn from './CacheUnusedColumn';
import TargetEnum from './TargetEnum';

/**
 * The CacheUnusedColumnsReport model module.
 * @module com.alterian.jo.model/CacheUnusedColumnsReport
 * @version 4.30.49
 */
class CacheUnusedColumnsReport {
    /**
     * Constructs a new <code>CacheUnusedColumnsReport</code>.
     * @alias module:com.alterian.jo.model/CacheUnusedColumnsReport
     */
    constructor() { 
        
        CacheUnusedColumnsReport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheUnusedColumnsReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheUnusedColumnsReport} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheUnusedColumnsReport} The populated <code>CacheUnusedColumnsReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheUnusedColumnsReport();

            if (data.hasOwnProperty('client')) {
                obj['client'] = ApiClient.convertToType(data['client'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = TargetEnum.constructFromObject(data['target']);
            }
            if (data.hasOwnProperty('tableName')) {
                obj['tableName'] = ApiClient.convertToType(data['tableName'], 'String');
            }
            if (data.hasOwnProperty('unusedColumns')) {
                obj['unusedColumns'] = ApiClient.convertToType(data['unusedColumns'], [CacheUnusedColumn]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheUnusedColumnsReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheUnusedColumnsReport</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['client'] && !(typeof data['client'] === 'string' || data['client'] instanceof String)) {
            throw new Error("Expected the field `client` to be a primitive type in the JSON string but got " + data['client']);
        }
        // ensure the json data is a string
        if (data['tableName'] && !(typeof data['tableName'] === 'string' || data['tableName'] instanceof String)) {
            throw new Error("Expected the field `tableName` to be a primitive type in the JSON string but got " + data['tableName']);
        }
        if (data['unusedColumns']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['unusedColumns'])) {
                throw new Error("Expected the field `unusedColumns` to be an array in the JSON data but got " + data['unusedColumns']);
            }
            // validate the optional field `unusedColumns` (array)
            for (const item of data['unusedColumns']) {
                CacheUnusedColumn.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} client
 */
CacheUnusedColumnsReport.prototype['client'] = undefined;

/**
 * @member {module:com.alterian.jo.model/TargetEnum} target
 */
CacheUnusedColumnsReport.prototype['target'] = undefined;

/**
 * @member {String} tableName
 */
CacheUnusedColumnsReport.prototype['tableName'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/CacheUnusedColumn>} unusedColumns
 */
CacheUnusedColumnsReport.prototype['unusedColumns'] = undefined;






export default CacheUnusedColumnsReport;

