/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CacheColumn from './CacheColumn';

/**
 * The CacheExecuteData model module.
 * @module com.alterian.jo.model/CacheExecuteData
 * @version 4.29.139
 */
class CacheExecuteData {
    /**
     * Constructs a new <code>CacheExecuteData</code>.
     * @alias module:com.alterian.jo.model/CacheExecuteData
     */
    constructor() { 
        
        CacheExecuteData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheExecuteData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/CacheExecuteData} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/CacheExecuteData} The populated <code>CacheExecuteData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheExecuteData();

            if (data.hasOwnProperty('wasApplied')) {
                obj['wasApplied'] = ApiClient.convertToType(data['wasApplied'], 'Boolean');
            }
            if (data.hasOwnProperty('columns')) {
                obj['columns'] = ApiClient.convertToType(data['columns'], [CacheColumn]);
            }
            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], [['String']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CacheExecuteData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CacheExecuteData</code>.
     */
    static validateJSON(data) {
        if (data['columns']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['columns'])) {
                throw new Error("Expected the field `columns` to be an array in the JSON data but got " + data['columns']);
            }
            // validate the optional field `columns` (array)
            for (const item of data['columns']) {
                CacheColumn.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['rows'])) {
            throw new Error("Expected the field `rows` to be an array in the JSON data but got " + data['rows']);
        }

        return true;
    }


}



/**
 * @member {Boolean} wasApplied
 */
CacheExecuteData.prototype['wasApplied'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/CacheColumn>} columns
 */
CacheExecuteData.prototype['columns'] = undefined;

/**
 * @member {Array.<Array.<String>>} rows
 */
CacheExecuteData.prototype['rows'] = undefined;






export default CacheExecuteData;

