/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClusterPutRequest model module.
 * @module com.alterian.jo.model/ClusterPutRequest
 * @version 4.29.139
 */
class ClusterPutRequest {
    /**
     * Constructs a new <code>ClusterPutRequest</code>.
     * @alias module:com.alterian.jo.model/ClusterPutRequest
     */
    constructor() { 
        
        ClusterPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClusterPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/ClusterPutRequest} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/ClusterPutRequest} The populated <code>ClusterPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterPutRequest();

            if (data.hasOwnProperty('attributeName')) {
                obj['attributeName'] = ApiClient.convertToType(data['attributeName'], 'String');
            }
            if (data.hasOwnProperty('attributeValue')) {
                obj['attributeValue'] = ApiClient.convertToType(data['attributeValue'], 'String');
            }
            if (data.hasOwnProperty('collectionName')) {
                obj['collectionName'] = ApiClient.convertToType(data['collectionName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClusterPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ClusterPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['attributeName'] && !(typeof data['attributeName'] === 'string' || data['attributeName'] instanceof String)) {
            throw new Error("Expected the field `attributeName` to be a primitive type in the JSON string but got " + data['attributeName']);
        }
        // ensure the json data is a string
        if (data['attributeValue'] && !(typeof data['attributeValue'] === 'string' || data['attributeValue'] instanceof String)) {
            throw new Error("Expected the field `attributeValue` to be a primitive type in the JSON string but got " + data['attributeValue']);
        }
        // ensure the json data is a string
        if (data['collectionName'] && !(typeof data['collectionName'] === 'string' || data['collectionName'] instanceof String)) {
            throw new Error("Expected the field `collectionName` to be a primitive type in the JSON string but got " + data['collectionName']);
        }

        return true;
    }


}



/**
 * The name of the setting to modify
 * @member {String} attributeName
 */
ClusterPutRequest.prototype['attributeName'] = undefined;

/**
 * The value to set
 * @member {String} attributeValue
 */
ClusterPutRequest.prototype['attributeValue'] = undefined;

/**
 * The name of the setting collection to modify
 * @member {String} collectionName
 */
ClusterPutRequest.prototype['collectionName'] = undefined;






export default ClusterPutRequest;

