/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RouteEntry from './RouteEntry';

/**
 * The ClusterResponseAllOfRouteTable model module.
 * @module com.alterian.jo.model/ClusterResponseAllOfRouteTable
 * @version 4.30.49
 */
class ClusterResponseAllOfRouteTable {
    /**
     * Constructs a new <code>ClusterResponseAllOfRouteTable</code>.
     * @alias module:com.alterian.jo.model/ClusterResponseAllOfRouteTable
     */
    constructor() { 
        
        ClusterResponseAllOfRouteTable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClusterResponseAllOfRouteTable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/ClusterResponseAllOfRouteTable} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/ClusterResponseAllOfRouteTable} The populated <code>ClusterResponseAllOfRouteTable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterResponseAllOfRouteTable();

            if (data.hasOwnProperty('routeEntries')) {
                obj['routeEntries'] = ApiClient.convertToType(data['routeEntries'], [RouteEntry]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClusterResponseAllOfRouteTable</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ClusterResponseAllOfRouteTable</code>.
     */
    static validateJSON(data) {
        if (data['routeEntries']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['routeEntries'])) {
                throw new Error("Expected the field `routeEntries` to be an array in the JSON data but got " + data['routeEntries']);
            }
            // validate the optional field `routeEntries` (array)
            for (const item of data['routeEntries']) {
                RouteEntry.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:com.alterian.jo.model/RouteEntry>} routeEntries
 */
ClusterResponseAllOfRouteTable.prototype['routeEntries'] = undefined;






export default ClusterResponseAllOfRouteTable;

