/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DataGridRow model module.
 * @module com.alterian.jo.model/DataGridRow
 * @version 4.29.139
 */
class DataGridRow {
    /**
     * Constructs a new <code>DataGridRow</code>.
     * @alias module:com.alterian.jo.model/DataGridRow
     */
    constructor() { 
        
        DataGridRow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DataGridRow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/DataGridRow} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/DataGridRow} The populated <code>DataGridRow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataGridRow();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [['String']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DataGridRow</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DataGridRow</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['data'])) {
            throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
        }

        return true;
    }


}



/**
 * @member {Array.<Array.<String>>} data
 */
DataGridRow.prototype['data'] = undefined;






export default DataGridRow;

