/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class KettleFieldType.
* @enum {}
* @readonly
*/
export default class KettleFieldType {
    
        /**
         * value: "BigNumber"
         * @const
         */
        "BigNumber" = "BigNumber";

    
        /**
         * value: "Binary"
         * @const
         */
        "Binary" = "Binary";

    
        /**
         * value: "blob"
         * @const
         */
        "blob" = "blob";

    
        /**
         * value: "Boolean"
         * @const
         */
        "Boolean" = "Boolean";

    
        /**
         * value: "counter"
         * @const
         */
        "counter" = "counter";

    
        /**
         * value: "Date"
         * @const
         */
        "Date" = "Date";

    
        /**
         * value: "Integer"
         * @const
         */
        "Integer" = "Integer";

    
        /**
         * value: "Internet Address"
         * @const
         */
        "Internet Address" = "Internet Address";

    
        /**
         * value: "Number"
         * @const
         */
        "Number" = "Number";

    
        /**
         * value: "String"
         * @const
         */
        "String" = "String";

    
        /**
         * value: "Timestamp"
         * @const
         */
        "Timestamp" = "Timestamp";

    

    /**
    * Returns a <code>KettleFieldType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.alterian.jo.model/KettleFieldType} The enum <code>KettleFieldType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

