/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LastModified model module.
 * @module com.alterian.jo.model/LastModified
 * @version 4.30.49
 */
class LastModified {
    /**
     * Constructs a new <code>LastModified</code>.
     * @alias module:com.alterian.jo.model/LastModified
     */
    constructor() { 
        
        LastModified.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LastModified</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/LastModified} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/LastModified} The populated <code>LastModified</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastModified();

            if (data.hasOwnProperty('lastModifiedDate')) {
                obj['lastModifiedDate'] = ApiClient.convertToType(data['lastModifiedDate'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedUser')) {
                obj['lastModifiedUser'] = ApiClient.convertToType(data['lastModifiedUser'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LastModified</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LastModified</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['lastModifiedDate'] && !(typeof data['lastModifiedDate'] === 'string' || data['lastModifiedDate'] instanceof String)) {
            throw new Error("Expected the field `lastModifiedDate` to be a primitive type in the JSON string but got " + data['lastModifiedDate']);
        }
        // ensure the json data is a string
        if (data['lastModifiedUser'] && !(typeof data['lastModifiedUser'] === 'string' || data['lastModifiedUser'] instanceof String)) {
            throw new Error("Expected the field `lastModifiedUser` to be a primitive type in the JSON string but got " + data['lastModifiedUser']);
        }

        return true;
    }


}



/**
 * When was this object last modified? Timestamp in ISO-8601 format
 * @member {String} lastModifiedDate
 */
LastModified.prototype['lastModifiedDate'] = undefined;

/**
 * What is the name of the user who last modified this object?
 * @member {String} lastModifiedUser
 */
LastModified.prototype['lastModifiedUser'] = undefined;






export default LastModified;

