/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MABVariant model module.
 * @module com.alterian.jo.model/MABVariant
 * @version 4.30.49
 */
class MABVariant {
    /**
     * Constructs a new <code>MABVariant</code>.
     * @alias module:com.alterian.jo.model/MABVariant
     * @extends Object
     */
    constructor() { 
        
        MABVariant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MABVariant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/MABVariant} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/MABVariant} The populated <code>MABVariant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MABVariant();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('staticVariant')) {
                obj['staticVariant'] = ApiClient.convertToType(data['staticVariant'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MABVariant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MABVariant</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['staticVariant'] && !(typeof data['staticVariant'] === 'string' || data['staticVariant'] instanceof String)) {
            throw new Error("Expected the field `staticVariant` to be a primitive type in the JSON string but got " + data['staticVariant']);
        }
        // ensure the json data is a string
        if (data['startDate'] && !(typeof data['startDate'] === 'string' || data['startDate'] instanceof String)) {
            throw new Error("Expected the field `startDate` to be a primitive type in the JSON string but got " + data['startDate']);
        }

        return true;
    }


}



/**
 * @member {String} staticVariant
 */
MABVariant.prototype['staticVariant'] = undefined;

/**
 * @member {String} startDate
 */
MABVariant.prototype['startDate'] = undefined;






export default MABVariant;

