/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OutputConnectorRealtimeOutputStepsInner from './OutputConnectorRealtimeOutputStepsInner';
import OutputField from './OutputField';

/**
 * The OutputConnector model module.
 * @module com.alterian.jo.model/OutputConnector
 * @version 4.30.49
 */
class OutputConnector {
    /**
     * Constructs a new <code>OutputConnector</code>.
     * @alias module:com.alterian.jo.model/OutputConnector
     */
    constructor() { 
        
        OutputConnector.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutputConnector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/OutputConnector} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/OutputConnector} The populated <code>OutputConnector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputConnector();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [OutputField]);
            }
            if (data.hasOwnProperty('realtimeOutputSteps')) {
                obj['realtimeOutputSteps'] = ApiClient.convertToType(data['realtimeOutputSteps'], [OutputConnectorRealtimeOutputStepsInner]);
            }
            if (data.hasOwnProperty('connectedInputs')) {
                obj['connectedInputs'] = ApiClient.convertToType(data['connectedInputs'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputConnector</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputConnector</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['fields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fields'])) {
                throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
            }
            // validate the optional field `fields` (array)
            for (const item of data['fields']) {
                OutputField.validateJSON(item);
            };
        }
        if (data['realtimeOutputSteps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['realtimeOutputSteps'])) {
                throw new Error("Expected the field `realtimeOutputSteps` to be an array in the JSON data but got " + data['realtimeOutputSteps']);
            }
            // validate the optional field `realtimeOutputSteps` (array)
            for (const item of data['realtimeOutputSteps']) {
                OutputConnectorRealtimeOutputStepsInner.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['connectedInputs'])) {
            throw new Error("Expected the field `connectedInputs` to be an array in the JSON data but got " + data['connectedInputs']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
OutputConnector.prototype['name'] = undefined;

/**
 * @member {Boolean} active
 */
OutputConnector.prototype['active'] = undefined;

/**
 * @member {Boolean} disabled
 */
OutputConnector.prototype['disabled'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/OutputField>} fields
 */
OutputConnector.prototype['fields'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/OutputConnectorRealtimeOutputStepsInner>} realtimeOutputSteps
 */
OutputConnector.prototype['realtimeOutputSteps'] = undefined;

/**
 * @member {Array.<String>} connectedInputs
 */
OutputConnector.prototype['connectedInputs'] = undefined;






export default OutputConnector;

