/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputConnectorRealtimeOutputStepsInner model module.
 * @module com.alterian.jo.model/OutputConnectorRealtimeOutputStepsInner
 * @version 4.29.139
 */
class OutputConnectorRealtimeOutputStepsInner {
    /**
     * Constructs a new <code>OutputConnectorRealtimeOutputStepsInner</code>.
     * @alias module:com.alterian.jo.model/OutputConnectorRealtimeOutputStepsInner
     */
    constructor() { 
        
        OutputConnectorRealtimeOutputStepsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutputConnectorRealtimeOutputStepsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/OutputConnectorRealtimeOutputStepsInner} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/OutputConnectorRealtimeOutputStepsInner} The populated <code>OutputConnectorRealtimeOutputStepsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputConnectorRealtimeOutputStepsInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputConnectorRealtimeOutputStepsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputConnectorRealtimeOutputStepsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
OutputConnectorRealtimeOutputStepsInner.prototype['name'] = undefined;






export default OutputConnectorRealtimeOutputStepsInner;

