/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueueMessage model module.
 * @module com.alterian.jo.model/QueueMessage
 * @version 4.30.49
 */
class QueueMessage {
    /**
     * Constructs a new <code>QueueMessage</code>.
     * @alias module:com.alterian.jo.model/QueueMessage
     */
    constructor() { 
        
        QueueMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueueMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/QueueMessage} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/QueueMessage} The populated <code>QueueMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueueMessage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('sentTimestamp')) {
                obj['sentTimestamp'] = ApiClient.convertToType(data['sentTimestamp'], 'String');
            }
            if (data.hasOwnProperty('bundleId')) {
                obj['bundleId'] = ApiClient.convertToType(data['bundleId'], 'Number');
            }
            if (data.hasOwnProperty('receipt')) {
                obj['receipt'] = ApiClient.convertToType(data['receipt'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], Object);
            }
            if (data.hasOwnProperty('nonjsonmessage')) {
                obj['nonjsonmessage'] = ApiClient.convertToType(data['nonjsonmessage'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueueMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueueMessage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['sentTimestamp'] && !(typeof data['sentTimestamp'] === 'string' || data['sentTimestamp'] instanceof String)) {
            throw new Error("Expected the field `sentTimestamp` to be a primitive type in the JSON string but got " + data['sentTimestamp']);
        }
        // ensure the json data is a string
        if (data['receipt'] && !(typeof data['receipt'] === 'string' || data['receipt'] instanceof String)) {
            throw new Error("Expected the field `receipt` to be a primitive type in the JSON string but got " + data['receipt']);
        }
        // ensure the json data is a string
        if (data['nonjsonmessage'] && !(typeof data['nonjsonmessage'] === 'string' || data['nonjsonmessage'] instanceof String)) {
            throw new Error("Expected the field `nonjsonmessage` to be a primitive type in the JSON string but got " + data['nonjsonmessage']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
QueueMessage.prototype['id'] = undefined;

/**
 * @member {String} sentTimestamp
 */
QueueMessage.prototype['sentTimestamp'] = undefined;

/**
 * @member {Number} bundleId
 */
QueueMessage.prototype['bundleId'] = undefined;

/**
 * @member {String} receipt
 */
QueueMessage.prototype['receipt'] = undefined;

/**
 * @member {Object} message
 */
QueueMessage.prototype['message'] = undefined;

/**
 * @member {String} nonjsonmessage
 */
QueueMessage.prototype['nonjsonmessage'] = undefined;






export default QueueMessage;

