/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuotaUsageHistory model module.
 * @module com.alterian.jo.model/QuotaUsageHistory
 * @version 4.29.139
 */
class QuotaUsageHistory {
    /**
     * Constructs a new <code>QuotaUsageHistory</code>.
     * @alias module:com.alterian.jo.model/QuotaUsageHistory
     * @param quotaused {Number} Quota used
     * @param timestamp {Date} Timestamp of quota usage
     */
    constructor(quotaused, timestamp) { 
        
        QuotaUsageHistory.initialize(this, quotaused, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quotaused, timestamp) { 
        obj['quotaused'] = quotaused;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>QuotaUsageHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/QuotaUsageHistory} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/QuotaUsageHistory} The populated <code>QuotaUsageHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuotaUsageHistory();

            if (data.hasOwnProperty('quotaused')) {
                obj['quotaused'] = ApiClient.convertToType(data['quotaused'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuotaUsageHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuotaUsageHistory</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuotaUsageHistory.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

QuotaUsageHistory.RequiredProperties = ["quotaused", "timestamp"];

/**
 * Quota used
 * @member {Number} quotaused
 */
QuotaUsageHistory.prototype['quotaused'] = undefined;

/**
 * Timestamp of quota usage
 * @member {Date} timestamp
 */
QuotaUsageHistory.prototype['timestamp'] = undefined;






export default QuotaUsageHistory;

