/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Parameter from './Parameter';
import TargetEnum from './TargetEnum';

/**
 * The RuleParamDetails model module.
 * @module com.alterian.jo.model/RuleParamDetails
 * @version 4.30.49
 */
class RuleParamDetails {
    /**
     * Constructs a new <code>RuleParamDetails</code>.
     * @alias module:com.alterian.jo.model/RuleParamDetails
     */
    constructor() { 
        
        RuleParamDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleParamDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/RuleParamDetails} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/RuleParamDetails} The populated <code>RuleParamDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleParamDetails();

            if (data.hasOwnProperty('RuleName')) {
                obj['RuleName'] = ApiClient.convertToType(data['RuleName'], 'String');
            }
            if (data.hasOwnProperty('Target')) {
                obj['Target'] = TargetEnum.constructFromObject(data['Target']);
            }
            if (data.hasOwnProperty('Client')) {
                obj['Client'] = ApiClient.convertToType(data['Client'], 'String');
            }
            if (data.hasOwnProperty('AllParameters')) {
                obj['AllParameters'] = ApiClient.convertToType(data['AllParameters'], [Parameter]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RuleParamDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RuleParamDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['RuleName'] && !(typeof data['RuleName'] === 'string' || data['RuleName'] instanceof String)) {
            throw new Error("Expected the field `RuleName` to be a primitive type in the JSON string but got " + data['RuleName']);
        }
        // ensure the json data is a string
        if (data['Client'] && !(typeof data['Client'] === 'string' || data['Client'] instanceof String)) {
            throw new Error("Expected the field `Client` to be a primitive type in the JSON string but got " + data['Client']);
        }
        if (data['AllParameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['AllParameters'])) {
                throw new Error("Expected the field `AllParameters` to be an array in the JSON data but got " + data['AllParameters']);
            }
            // validate the optional field `AllParameters` (array)
            for (const item of data['AllParameters']) {
                Parameter.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} RuleName
 */
RuleParamDetails.prototype['RuleName'] = undefined;

/**
 * @member {module:com.alterian.jo.model/TargetEnum} Target
 */
RuleParamDetails.prototype['Target'] = undefined;

/**
 * @member {String} Client
 */
RuleParamDetails.prototype['Client'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/Parameter>} AllParameters
 */
RuleParamDetails.prototype['AllParameters'] = undefined;






export default RuleParamDetails;

