/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataGridDetails from './DataGridDetails';

/**
 * The RuleGroupParameterDefaultValueOneOf model module.
 * @module com.alterian.jo.model/RuleGroupParameterDefaultValueOneOf
 * @version 4.30.49
 */
class RuleGroupParameterDefaultValueOneOf {
    /**
     * Constructs a new <code>RuleGroupParameterDefaultValueOneOf</code>.
     * @alias module:com.alterian.jo.model/RuleGroupParameterDefaultValueOneOf
     */
    constructor() { 
        
        RuleGroupParameterDefaultValueOneOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleGroupParameterDefaultValueOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/RuleGroupParameterDefaultValueOneOf} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/RuleGroupParameterDefaultValueOneOf} The populated <code>RuleGroupParameterDefaultValueOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleGroupParameterDefaultValueOneOf();

            if (data.hasOwnProperty('detailsOfDataGrid')) {
                obj['detailsOfDataGrid'] = DataGridDetails.constructFromObject(data['detailsOfDataGrid']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RuleGroupParameterDefaultValueOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RuleGroupParameterDefaultValueOneOf</code>.
     */
    static validateJSON(data) {
        // validate the optional field `detailsOfDataGrid`
        if (data['detailsOfDataGrid']) { // data not null
          DataGridDetails.validateJSON(data['detailsOfDataGrid']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.jo.model/DataGridDetails} detailsOfDataGrid
 */
RuleGroupParameterDefaultValueOneOf.prototype['detailsOfDataGrid'] = undefined;






export default RuleGroupParameterDefaultValueOneOf;

