/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TargetEnum from './TargetEnum';

/**
 * The RuleGroupDestinationTarget model module.
 * @module com.alterian.jo.model/RuleGroupDestinationTarget
 * @version 4.30.49
 */
class RuleGroupDestinationTarget {
    /**
     * Constructs a new <code>RuleGroupDestinationTarget</code>.
     * @alias module:com.alterian.jo.model/RuleGroupDestinationTarget
     */
    constructor() { 
        
        RuleGroupDestinationTarget.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleGroupDestinationTarget</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/RuleGroupDestinationTarget} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/RuleGroupDestinationTarget} The populated <code>RuleGroupDestinationTarget</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleGroupDestinationTarget();

            if (data.hasOwnProperty('destinationtarget')) {
                obj['destinationtarget'] = TargetEnum.constructFromObject(data['destinationtarget']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RuleGroupDestinationTarget</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RuleGroupDestinationTarget</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:com.alterian.jo.model/TargetEnum} destinationtarget
 */
RuleGroupDestinationTarget.prototype['destinationtarget'] = undefined;






export default RuleGroupDestinationTarget;

