/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServerSettingsAttribute from './ServerSettingsAttribute';

/**
 * The ServerSettings model module.
 * @module com.alterian.jo.model/ServerSettings
 * @version 4.30.49
 */
class ServerSettings {
    /**
     * Constructs a new <code>ServerSettings</code>.
     * @alias module:com.alterian.jo.model/ServerSettings
     */
    constructor() { 
        
        ServerSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServerSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/ServerSettings} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/ServerSettings} The populated <code>ServerSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerSettings();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], [ServerSettingsAttribute]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServerSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServerSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['attributes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributes'])) {
                throw new Error("Expected the field `attributes` to be an array in the JSON data but got " + data['attributes']);
            }
            // validate the optional field `attributes` (array)
            for (const item of data['attributes']) {
                ServerSettingsAttribute.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} name
 */
ServerSettings.prototype['name'] = undefined;

/**
 * @member {Array.<module:com.alterian.jo.model/ServerSettingsAttribute>} attributes
 */
ServerSettings.prototype['attributes'] = undefined;






export default ServerSettings;

