/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServerSettingsAttribute model module.
 * @module com.alterian.jo.model/ServerSettingsAttribute
 * @version 4.30.49
 */
class ServerSettingsAttribute {
    /**
     * Constructs a new <code>ServerSettingsAttribute</code>.
     * @alias module:com.alterian.jo.model/ServerSettingsAttribute
     */
    constructor() { 
        
        ServerSettingsAttribute.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServerSettingsAttribute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/ServerSettingsAttribute} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/ServerSettingsAttribute} The populated <code>ServerSettingsAttribute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerSettingsAttribute();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isWriteable')) {
                obj['isWriteable'] = ApiClient.convertToType(data['isWriteable'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServerSettingsAttribute</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServerSettingsAttribute</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
ServerSettingsAttribute.prototype['name'] = undefined;

/**
 * @member {String} value
 */
ServerSettingsAttribute.prototype['value'] = undefined;

/**
 * @member {Boolean} isWriteable
 */
ServerSettingsAttribute.prototype['isWriteable'] = undefined;






export default ServerSettingsAttribute;

