/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TargetEnum from './TargetEnum';

/**
 * The TargetValue model module.
 * @module com.alterian.jo.model/TargetValue
 * @version 4.29.139
 */
class TargetValue {
    /**
     * Constructs a new <code>TargetValue</code>.
     * @alias module:com.alterian.jo.model/TargetValue
     * @param target {module:com.alterian.jo.model/TargetEnum} 
     * @param value {String} the parameter value
     */
    constructor(target, value) { 
        
        TargetValue.initialize(this, target, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, target, value) { 
        obj['target'] = target;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TargetValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/TargetValue} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/TargetValue} The populated <code>TargetValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TargetValue();

            if (data.hasOwnProperty('target')) {
                obj['target'] = TargetEnum.constructFromObject(data['target']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TargetValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TargetValue</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TargetValue.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

TargetValue.RequiredProperties = ["target", "value"];

/**
 * @member {module:com.alterian.jo.model/TargetEnum} target
 */
TargetValue.prototype['target'] = undefined;

/**
 * the parameter value
 * @member {String} value
 */
TargetValue.prototype['value'] = undefined;






export default TargetValue;

