/**
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataGridDetails from './DataGridDetails';

/**
 * The TemplatePublishSettings model module.
 * @module com.alterian.jo.model/TemplatePublishSettings
 * @version 4.30.49
 */
class TemplatePublishSettings {
    /**
     * Constructs a new <code>TemplatePublishSettings</code>.
     * @alias module:com.alterian.jo.model/TemplatePublishSettings
     * @extends Object
     */
    constructor() { 
        
        TemplatePublishSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplatePublishSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.jo.model/TemplatePublishSettings} obj Optional instance to populate.
     * @return {module:com.alterian.jo.model/TemplatePublishSettings} The populated <code>TemplatePublishSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplatePublishSettings();

            ApiClient.constructFromObject(data, obj, 'String');
            

            if (data.hasOwnProperty('detailsOfDataGrid')) {
                obj['detailsOfDataGrid'] = DataGridDetails.constructFromObject(data['detailsOfDataGrid']);
            }
            if (data.hasOwnProperty('rulename')) {
                obj['rulename'] = ApiClient.convertToType(data['rulename'], 'String');
            }
            if (data.hasOwnProperty('rulegroups')) {
                obj['rulegroups'] = ApiClient.convertToType(data['rulegroups'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TemplatePublishSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TemplatePublishSettings</code>.
     */
    static validateJSON(data) {
        // validate the optional field `detailsOfDataGrid`
        if (data['detailsOfDataGrid']) { // data not null
          DataGridDetails.validateJSON(data['detailsOfDataGrid']);
        }
        // ensure the json data is a string
        if (data['rulename'] && !(typeof data['rulename'] === 'string' || data['rulename'] instanceof String)) {
            throw new Error("Expected the field `rulename` to be a primitive type in the JSON string but got " + data['rulename']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['rulegroups'])) {
            throw new Error("Expected the field `rulegroups` to be an array in the JSON data but got " + data['rulegroups']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.jo.model/DataGridDetails} detailsOfDataGrid
 */
TemplatePublishSettings.prototype['detailsOfDataGrid'] = undefined;

/**
 * @member {String} rulename
 */
TemplatePublishSettings.prototype['rulename'] = undefined;

/**
 * @member {Array.<String>} rulegroups
 */
TemplatePublishSettings.prototype['rulegroups'] = undefined;






export default TemplatePublishSettings;

